export const GET_DOWNLOAD_QUEUE_STARTED = 'queue/GET_DOWNLOAD_QUEUE_STARTED';
export const GET_DOWNLOAD_QUEUE_COMPLETED = 'queue/GET_DOWNLOAD_QUEUE_COMPLETED';
export const GET_DOWNLOAD_QUEUE_FAILED = 'queue/GET_DOWNLOAD_QUEUE_FAILED';

export const GET_RECENTLY_DOWNLOAD_STARTED = 'queue/GET_RECENTLY_DOWNLOAD_STARTED';
export const GET_RECENTLY_DOWNLOAD_COMPLETED = 'queue/GET_RECENTLY_DOWNLOAD_COMPLETED';
export const GET_RECENTLY_DOWNLOAD_FAILED = 'queue/GET_RECENTLY_DOWNLOAD_FAILED';