export const GET_SOURCES_STARTED = 'source/GET_SOURCES_STARTED';
export const GET_SOURCES_COMPLETED = 'source/GET_SOURCES_COMPLETED';
export const GET_SOURCES_FAILED = 'source/GET_SOURCES_FAILED';

export const SET_SELECTED_SOURCE = 'source/SET_SELECTED_SOURCE';

export const ADD_SOURCE_STARTED = 'source/ADD_SOURCE_STARTED';
export const ADD_SOURCE_COMPLETED = 'source/ADD_SOURCE_COMPLETED';
export const ADD_SOURCE_FAILED = 'source/ADD_SOURCE_FAILED';

export const ADD_SOURCE_RETRY = 'source/ADD_SOURCE_RETRY';
export const ADD_SOURCE_RESET = 'source/ADD_SOURCE_RESET';