export const GET_SOURCES_STARTED = 'sources/GET_SOURCES_STARTED';
export const GET_SOURCES_COMPLETED = 'sources/GET_SOURCES_COMPLETED';
export const GET_SOURCES_FAILED = 'sources/GET_SOURCES_FAILED';

export const GET_SINGLE_SOURCE_STARTED = 'sources/GET_SINGLE_SOURCE_STARTED';
export const GET_SINGLE_SOURCE_COMPLETED = 'sources/GET_SINGLE_SOURCE_COMPLETED';
export const GET_SINGLE_SOURCE_FAILED = 'sources/GET_SINGLE_SOURCE_FAILED';

export const SET_SELECTED_SOURCE = 'sources/SET_SELECTED_SOURCE';

export const ADD_SOURCE_STARTED = 'sources/ADD_SOURCE_STARTED';
export const ADD_SOURCE_COMPLETED = 'sources/ADD_SOURCE_COMPLETED';
export const ADD_SOURCE_FAILED = 'sources/ADD_SOURCE_FAILED';

export const ADD_SOURCE_RETRY = 'sources/ADD_SOURCE_RETRY';
export const ADD_SOURCE_RESET = 'sources/ADD_SOURCE_RESET';