export const GET_DASHBOARD_QUICKSTATS_STARTED = 'dashboard/GET_DASHBOARD_QUICKSTATS_STARTED';
export const GET_DASHBOARD_QUICKSTATS_COMPLETED = 'dashboard/GET_DASHBOARD_QUICKSTATS_COMPLETED';
export const GET_DASHBOARD_QUICKSTATS_FAILED = 'dashboard/GET_DASHBOARD_QUICKSTATS_FAILED';

export const GET_RECENTLY_MONITORED_STARTED = 'dashboard/GET_RECENTLY_MONITORED_STARTED';
export const GET_RECENTLY_MONITORED_COMPLETED = 'dashboard/GET_RECENTLY_MONITORED_COMPLETED';
export const GET_RECENTLY_MONITORED_FAILED = 'dashboard/GET_RECENTLY_MONITORED_FAILED';