export const SET_ACTIVITY_VIEW_TYPE = 'activity/SET_ACTIVITY_VIEW_TYPE';

export const GET_DOWNLOAD_QUEUE_STARTED = 'activity/GET_DOWNLOAD_QUEUE_STARTED';
export const GET_DOWNLOAD_QUEUE_COMPLETED = 'activity/GET_DOWNLOAD_QUEUE_COMPLETED';
export const GET_DOWNLOAD_QUEUE_FAILED = 'activity/GET_DOWNLOAD_QUEUE_FAILED';

export const GET_RECENTLY_DOWNLOAD_STARTED = 'activity/GET_RECENTLY_DOWNLOAD_STARTED';
export const GET_RECENTLY_DOWNLOAD_COMPLETED = 'activity/GET_RECENTLY_DOWNLOAD_COMPLETED';
export const GET_RECENTLY_DOWNLOAD_FAILED = 'activity/GET_RECENTLY_DOWNLOAD_FAILED';